{
    "GSD": {
        "alias": "CVE-2019-6446",
        "description": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.",
        "id": "GSD-2019-6446"
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2019-6446",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "n/a",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "n/a"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "n/a"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "n/a"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
                        "refsource": "MISC",
                        "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                    },
                    {
                        "name": "106670",
                        "refsource": "BID",
                        "url": "http://www.securityfocus.com/bid/106670"
                    },
                    {
                        "name": "https://github.com/numpy/numpy/issues/12759",
                        "refsource": "MISC",
                        "url": "https://github.com/numpy/numpy/issues/12759"
                    },
                    {
                        "name": "FEDORA-2019-1dfe95a864",
                        "refsource": "FEDORA",
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
                    },
                    {
                        "name": "openSUSE-SU-2019:2227",
                        "refsource": "SUSE",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                    },
                    {
                        "name": "openSUSE-SU-2019:2225",
                        "refsource": "SUSE",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                    },
                    {
                        "name": "openSUSE-SU-2019:2259",
                        "refsource": "SUSE",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                    },
                    {
                        "name": "RHSA-2019:3335",
                        "refsource": "REDHAT",
                        "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                    },
                    {
                        "name": "RHSA-2019:3704",
                        "refsource": "REDHAT",
                        "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                    }
                ]
            }
        },
        "gitlab.com": {
            "advisories": [
                {
                    "affected_range": "<1.16.3",
                    "affected_versions": "All versions before 1.16.3",
                    "credit": "nanshihui",
                    "cvss_v2": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
                    "cvss_v3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-502",
                        "CWE-937"
                    ],
                    "date": "2019-09-30",
                    "description": "An unsafe use of the pickle Python module allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a `numpy.load` call. NOTE: third parties dispute this issue because it is a behavior that might have legitimate applications in (for example) loading serialized Python object arrays from trusted and authenticated sources.",
                    "fixed_versions": [
                        "1.16.3"
                    ],
                    "identifier": "CVE-2019-6446",
                    "identifiers": [
                        "CVE-2019-6446"
                    ],
                    "package_slug": "pypi/numpy",
                    "pubdate": "2019-01-16",
                    "solution": "Upgrade to version 1.16.3 or above",
                    "title": "Arbitrary Code Execution",
                    "urls": [
                        "http://www.securityfocus.com/bid/106670",
                        "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
                        "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6446",
                        "https://cwe.mitre.org/data/definitions/94.html",
                        "https://github.com/numpy/numpy/issues/12759"
                    ],
                    "uuid": "b8804275-0868-45f4-9ab6-bfd68ad34e00"
                }
            ]
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": [
                    {
                        "children": [],
                        "cpe_match": [
                            {
                                "cpe23Uri": "cpe:2.3:a:numpy:numpy:*:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "versionEndIncluding": "1.16.0",
                                "vulnerable": true
                            }
                        ],
                        "operator": "OR"
                    },
                    {
                        "children": [],
                        "cpe_match": [
                            {
                                "cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:30:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            }
                        ],
                        "operator": "OR"
                    }
                ]
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2019-6446"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "en",
                                    "value": "CWE-502"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/numpy/numpy/issues/12759",
                            "refsource": "MISC",
                            "tags": [
                                "Exploit",
                                "Issue Tracking",
                                "Third Party Advisory"
                            ],
                            "url": "https://github.com/numpy/numpy/issues/12759"
                        },
                        {
                            "name": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
                            "refsource": "MISC",
                            "tags": [
                                "Exploit",
                                "Issue Tracking",
                                "Third Party Advisory"
                            ],
                            "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                        },
                        {
                            "name": "106670",
                            "refsource": "BID",
                            "tags": [
                                "Third Party Advisory",
                                "VDB Entry"
                            ],
                            "url": "http://www.securityfocus.com/bid/106670"
                        },
                        {
                            "name": "FEDORA-2019-1dfe95a864",
                            "refsource": "FEDORA",
                            "tags": [
                                "Third Party Advisory"
                            ],
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
                        },
                        {
                            "name": "openSUSE-SU-2019:2227",
                            "refsource": "SUSE",
                            "tags": [],
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                        },
                        {
                            "name": "openSUSE-SU-2019:2225",
                            "refsource": "SUSE",
                            "tags": [],
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                        },
                        {
                            "name": "openSUSE-SU-2019:2259",
                            "refsource": "SUSE",
                            "tags": [],
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                        },
                        {
                            "name": "RHSA-2019:3335",
                            "refsource": "REDHAT",
                            "tags": [],
                            "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                        },
                        {
                            "name": "RHSA-2019:3704",
                            "refsource": "REDHAT",
                            "tags": [],
                            "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                        }
                    ]
                }
            },
            "impact": {
                "baseMetricV2": {
                    "acInsufInfo": false,
                    "cvssV2": {
                        "accessComplexity": "LOW",
                        "accessVector": "NETWORK",
                        "authentication": "NONE",
                        "availabilityImpact": "PARTIAL",
                        "baseScore": 7.5,
                        "confidentialityImpact": "PARTIAL",
                        "integrityImpact": "PARTIAL",
                        "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
                        "version": "2.0"
                    },
                    "exploitabilityScore": 10.0,
                    "impactScore": 6.4,
                    "obtainAllPrivilege": false,
                    "obtainOtherPrivilege": false,
                    "obtainUserPrivilege": false,
                    "severity": "HIGH",
                    "userInteractionRequired": false
                },
                "baseMetricV3": {
                    "cvssV3": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 9.8,
                        "baseSeverity": "CRITICAL",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                        "version": "3.0"
                    },
                    "exploitabilityScore": 3.9,
                    "impactScore": 5.9
                }
            },
            "lastModifiedDate": "2019-10-01T00:15Z",
            "publishedDate": "2019-01-16T05:29Z"
        }
    }
}