{
    "GSD": {
        "alias": "CVE-2022-35934",
        "description": "TensorFlow is an open source platform for machine learning. The implementation of tf.reshape op in TensorFlow is vulnerable to a denial of service via CHECK-failure (assertion failure) caused by overflowing the number of elements in a tensor. This issue has been patched in GitHub commit 61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
        "id": "GSD-2022-35934",
        "references": [
            "https://www.suse.com/security/cve/CVE-2022-35934.html"
        ]
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "security-advisories@github.com",
                "ID": "CVE-2022-35934",
                "STATE": "PUBLIC",
                "TITLE": "`CHECK` failure in tf.reshape in Tensorflow"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "tensorflow",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "< 2.7.2"
                                                },
                                                {
                                                    "version_value": ">= 2.8.0, < 2.8.1"
                                                },
                                                {
                                                    "version_value": ">= 2.9.0, < 2.9.1"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "tensorflow"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "TensorFlow is an open source platform for machine learning. The implementation of tf.reshape op in TensorFlow is vulnerable to a denial of service via CHECK-failure (assertion failure) caused by overflowing the number of elements in a tensor. This issue has been patched in GitHub commit 61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue."
                    }
                ]
            },
            "impact": {
                "cvss": {
                    "attackComplexity": "HIGH",
                    "attackVector": "NETWORK",
                    "availabilityImpact": "HIGH",
                    "baseScore": 5.9,
                    "baseSeverity": "MEDIUM",
                    "confidentialityImpact": "NONE",
                    "integrityImpact": "NONE",
                    "privilegesRequired": "NONE",
                    "scope": "UNCHANGED",
                    "userInteraction": "NONE",
                    "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "version": "3.1"
                }
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "CWE-617: Reachable Assertion"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f4w6-h4f5-wx45",
                        "refsource": "CONFIRM",
                        "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f4w6-h4f5-wx45"
                    },
                    {
                        "name": "https://github.com/tensorflow/tensorflow/commit/61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555",
                        "refsource": "MISC",
                        "url": "https://github.com/tensorflow/tensorflow/commit/61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555"
                    }
                ]
            },
            "source": {
                "advisory": "GHSA-f4w6-h4f5-wx45",
                "discovery": "UNKNOWN"
            }
        },
        "gitlab.com": {
            "advisories": [
                {
                    "affected_range": "<2.7.2||>=2.8.0,<2.8.1||>=2.9.0,<2.9.1",
                    "affected_versions": "All versions before 2.7.2, all versions starting from 2.8.0 before 2.8.1, all versions starting from 2.9.0 before 2.9.1",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-937"
                    ],
                    "date": "2022-09-16",
                    "description": "TensorFlow is an open source platform for machine learning. The implementation of tf.reshape op in TensorFlow is vulnerable to a denial of service via CHECK-failure (assertion failure) caused by overflowing the number of elements in a tensor. This issue has been patched in GitHub commit 61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
                    "fixed_versions": [
                        "2.7.2",
                        "2.8.1",
                        "2.9.1"
                    ],
                    "identifier": "CVE-2022-35934",
                    "identifiers": [
                        "GHSA-f4w6-h4f5-wx45",
                        "CVE-2022-35934"
                    ],
                    "not_impacted": "All versions starting from 2.7.2 before 2.8.0, all versions starting from 2.8.1 before 2.9.0, all versions starting from 2.9.1",
                    "package_slug": "pypi/tensorflow-cpu",
                    "pubdate": "2022-09-16",
                    "solution": "Upgrade to versions 2.7.2, 2.8.1, 2.9.1 or above.",
                    "title": "TensorFlow vulnerable to `CHECK` failure in tf.reshape via overflows",
                    "urls": [
                        "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f4w6-h4f5-wx45",
                        "https://github.com/tensorflow/tensorflow/commit/61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555",
                        "https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0",
                        "https://github.com/advisories/GHSA-f4w6-h4f5-wx45"
                    ],
                    "uuid": "5ecfedc9-d293-4c7d-8f7c-635ec4dcd7c2"
                },
                {
                    "affected_range": "<2.7.2||>=2.8.0,<2.8.1||>=2.9.0,<2.9.1",
                    "affected_versions": "All versions before 2.7.2, all versions starting from 2.8.0 before 2.8.1, all versions starting from 2.9.0 before 2.9.1",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-937"
                    ],
                    "date": "2022-09-16",
                    "description": "TensorFlow is an open source platform for machine learning. The implementation of tf.reshape op in TensorFlow is vulnerable to a denial of service via CHECK-failure (assertion failure) caused by overflowing the number of elements in a tensor. This issue has been patched in GitHub commit 61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
                    "fixed_versions": [
                        "2.7.2",
                        "2.8.1",
                        "2.9.1"
                    ],
                    "identifier": "CVE-2022-35934",
                    "identifiers": [
                        "GHSA-f4w6-h4f5-wx45",
                        "CVE-2022-35934"
                    ],
                    "not_impacted": "All versions starting from 2.7.2 before 2.8.0, all versions starting from 2.8.1 before 2.9.0, all versions starting from 2.9.1",
                    "package_slug": "pypi/tensorflow-gpu",
                    "pubdate": "2022-09-16",
                    "solution": "Upgrade to versions 2.7.2, 2.8.1, 2.9.1 or above.",
                    "title": "TensorFlow vulnerable to `CHECK` failure in tf.reshape via overflows",
                    "urls": [
                        "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f4w6-h4f5-wx45",
                        "https://github.com/tensorflow/tensorflow/commit/61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555",
                        "https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0",
                        "https://github.com/advisories/GHSA-f4w6-h4f5-wx45"
                    ],
                    "uuid": "90ab049f-4c3d-4ec6-bd4e-d92b94e71f39"
                },
                {
                    "affected_range": ">=2.7.0,<2.7.2||>=2.8.0,<2.8.1||>=2.9.0,<2.9.1||==2.10",
                    "affected_versions": "All versions starting from 2.7.0 before 2.7.2, all versions starting from 2.8.0 before 2.8.1, all versions starting from 2.9.0 before 2.9.1, version 2.10",
                    "cvss_v3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-617",
                        "CWE-937"
                    ],
                    "date": "2022-09-20",
                    "description": "TensorFlow is an open source platform for machine learning. The implementation of tf.reshape op in TensorFlow is vulnerable to a denial of service via CHECK-failure (assertion failure) caused by overflowing the number of elements in a tensor. This issue has been patched in GitHub commit 61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
                    "fixed_versions": [
                        "2.7.2",
                        "2.8.1",
                        "2.9.1"
                    ],
                    "identifier": "CVE-2022-35934",
                    "identifiers": [
                        "CVE-2022-35934",
                        "GHSA-f4w6-h4f5-wx45"
                    ],
                    "not_impacted": "All versions before 2.7.0, all versions starting from 2.7.2 before 2.8.0, all versions starting from 2.8.1 before 2.9.0, all versions starting from 2.9.1 before 2.10, all versions after 2.10",
                    "package_slug": "pypi/tensorflow",
                    "pubdate": "2022-09-16",
                    "solution": "Upgrade to versions 2.7.2, 2.8.1, 2.9.1 or above.",
                    "title": "TensorFlow vulnerable to `CHECK` failure in tf.reshape via overflows",
                    "urls": [
                        "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f4w6-h4f5-wx45",
                        "https://github.com/tensorflow/tensorflow/commit/61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555",
                        "https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0",
                        "https://github.com/advisories/GHSA-f4w6-h4f5-wx45"
                    ],
                    "uuid": "cb903399-2789-4083-9e33-a69a99f01ca0"
                }
            ]
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": [
                    {
                        "children": [],
                        "cpe_match": [
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "versionEndExcluding": "2.7.2",
                                "versionStartIncluding": "2.7.0",
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "versionEndExcluding": "2.8.1",
                                "versionStartIncluding": "2.8.0",
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc1:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc2:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc3:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc0:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "versionEndExcluding": "2.9.1",
                                "versionStartIncluding": "2.9.0",
                                "vulnerable": true
                            }
                        ],
                        "operator": "OR"
                    }
                ]
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "security-advisories@github.com",
                    "ID": "CVE-2022-35934"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "TensorFlow is an open source platform for machine learning. The implementation of tf.reshape op in TensorFlow is vulnerable to a denial of service via CHECK-failure (assertion failure) caused by overflowing the number of elements in a tensor. This issue has been patched in GitHub commit 61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "en",
                                    "value": "CWE-617"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/tensorflow/tensorflow/commit/61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555",
                            "refsource": "MISC",
                            "tags": [
                                "Patch",
                                "Third Party Advisory"
                            ],
                            "url": "https://github.com/tensorflow/tensorflow/commit/61f0f9b94df8c0411f0ad0ecc2fec2d3f3c33555"
                        },
                        {
                            "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f4w6-h4f5-wx45",
                            "refsource": "CONFIRM",
                            "tags": [
                                "Patch",
                                "Third Party Advisory"
                            ],
                            "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f4w6-h4f5-wx45"
                        }
                    ]
                }
            },
            "impact": {
                "baseMetricV3": {
                    "cvssV3": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.5,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    },
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                }
            },
            "lastModifiedDate": "2022-09-20T16:42Z",
            "publishedDate": "2022-09-16T20:15Z"
        }
    }
}