{
    "GSD": {
        "alias": "CVE-2022-40898",
        "id": "GSD-2022-40898",
        "references": [
            "https://www.suse.com/security/cve/CVE-2022-40898.html",
            "https://ubuntu.com/security/CVE-2022-40898"
        ]
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2022-40898",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "n/a",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "n/a"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "n/a"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "n/a"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://pypi.org/project/wheel/",
                        "refsource": "MISC",
                        "url": "https://pypi.org/project/wheel/"
                    },
                    {
                        "name": "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
                        "refsource": "MISC",
                        "url": "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18"
                    },
                    {
                        "name": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
                        "refsource": "MISC",
                        "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
                    }
                ]
            }
        },
        "gitlab.com": {
            "advisories": [
                {
                    "affected_range": "<0.38.1",
                    "affected_versions": "All versions before 0.38.1",
                    "cvss_v3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-937"
                    ],
                    "date": "2022-12-30",
                    "description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
                    "fixed_versions": [
                        "0.38.1"
                    ],
                    "identifier": "CVE-2022-40898",
                    "identifiers": [
                        "CVE-2022-40898",
                        "GHSA-qwmp-2cf2-g9g6"
                    ],
                    "not_impacted": "All versions starting from 0.38.1",
                    "package_slug": "pypi/wheel",
                    "pubdate": "2022-12-23",
                    "solution": "Upgrade to version 0.38.1 or above.",
                    "title": "pypa/wheel vulnerable to Regular Expression denial of service (ReDoS)",
                    "urls": [
                        "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
                        "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
                        "https://pypi.org/project/wheel/",
                        "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
                        "https://pyup.io/vulnerabilities/CVE-2022-40898/51499/",
                        "https://github.com/advisories/GHSA-qwmp-2cf2-g9g6"
                    ],
                    "uuid": "37b7fe90-ce17-4928-9153-79d00a8cf7ee"
                }
            ]
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": [
                    {
                        "children": [],
                        "cpe_match": [
                            {
                                "cpe23Uri": "cpe:2.3:a:wheel_project:wheel:*:*:*:*:*:python:*:*",
                                "cpe_name": [],
                                "versionEndExcluding": "0.38.1",
                                "vulnerable": true
                            }
                        ],
                        "operator": "OR"
                    }
                ]
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2022-40898"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "en",
                                    "value": "NVD-CWE-noinfo"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://pypi.org/project/wheel/",
                            "refsource": "MISC",
                            "tags": [
                                "Product",
                                "Third Party Advisory"
                            ],
                            "url": "https://pypi.org/project/wheel/"
                        },
                        {
                            "name": "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
                            "refsource": "MISC",
                            "tags": [
                                "Third Party Advisory"
                            ],
                            "url": "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18"
                        },
                        {
                            "name": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
                            "refsource": "MISC",
                            "tags": [
                                "Exploit",
                                "Vendor Advisory"
                            ],
                            "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
                        }
                    ]
                }
            },
            "impact": {
                "baseMetricV3": {
                    "cvssV3": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.5,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    },
                    "exploitabilityScore": 3.9,
                    "impactScore": 3.6
                }
            },
            "lastModifiedDate": "2022-12-30T22:15Z",
            "publishedDate": "2022-12-23T00:15Z"
        }
    }
}