{
    "GSD": {
        "alias": "CVE-2023-1436",
        "id": "GSD-2023-1436"
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "security@jfrog.com",
                "ID": "CVE-2023-1436",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "jettison",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_affected": "<",
                                                    "version_name": "0",
                                                    "version_value": "1.5.4"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "jettison"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "An infinite recursion is triggered in Jettison when constructing a JSONArray from a Collection that contains a self-reference in one of its elements. This leads to a StackOverflowError exception being thrown."
                    }
                ]
            },
            "impact": {
                "cvss": [
                    {
                        "attackComplexity": "HIGH",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 5.9,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "cweId": "CWE-674",
                                "lang": "eng",
                                "value": "CWE-674 Uncontrolled Recursion"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/",
                        "refsource": "MISC",
                        "url": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/"
                    }
                ]
            },
            "source": {
                "discovery": "INTERNAL"
            }
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": []
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "security@jfrog.com",
                    "ID": "CVE-2023-1436"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "An infinite recursion is triggered in Jettison when constructing a JSONArray from a Collection that contains a self-reference in one of its elements. This leads to a StackOverflowError exception being thrown."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": []
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/"
                        }
                    ]
                }
            },
            "impact": {},
            "lastModifiedDate": "2023-03-22T12:48Z",
            "publishedDate": "2023-03-22T06:15Z"
        }
    }
}