{
    "GSD": {
        "alias": "CVE-2016-4989",
        "description": "setroubleshoot allows local users to bypass an intended container protection mechanism and execute arbitrary commands by (1) triggering an SELinux denial with a crafted file name, which is handled by the _set_tpath function in audit_data.py or via a crafted (2) local_id or (3) analysis_id field in a crafted XML document to the run_fix function in SetroubleshootFixit.py, related to the subprocess.check_output and commands.getstatusoutput functions, a different vulnerability than CVE-2016-4445.",
        "id": "GSD-2016-4989",
        "references": [
            "https://www.suse.com/security/cve/CVE-2016-4989.html",
            "https://access.redhat.com/errata/RHSA-2016:1293",
            "https://access.redhat.com/errata/RHSA-2016:1267"
        ]
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "secalert@redhat.com",
                "ID": "CVE-2016-4989",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "n/a",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "n/a"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "n/a"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "setroubleshoot allows local users to bypass an intended container protection mechanism and execute arbitrary commands by (1) triggering an SELinux denial with a crafted file name, which is handled by the _set_tpath function in audit_data.py or via a crafted (2) local_id or (3) analysis_id field in a crafted XML document to the run_fix function in SetroubleshootFixit.py, related to the subprocess.check_output and commands.getstatusoutput functions, a different vulnerability than CVE-2016-4445."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "n/a"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461",
                        "refsource": "CONFIRM",
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461"
                    },
                    {
                        "name": "RHSA-2016:1267",
                        "refsource": "REDHAT",
                        "url": "https://rhn.redhat.com/errata/RHSA-2016-1267.html"
                    },
                    {
                        "name": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad",
                        "refsource": "CONFIRM",
                        "url": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad"
                    },
                    {
                        "name": "[oss-security] 20160621 SELinux troubles",
                        "refsource": "MLIST",
                        "url": "http://seclists.org/oss-sec/2016/q2/574"
                    },
                    {
                        "name": "RHSA-2016:1293",
                        "refsource": "REDHAT",
                        "url": "https://access.redhat.com/errata/RHSA-2016:1293"
                    },
                    {
                        "name": "1036144",
                        "refsource": "SECTRACK",
                        "url": "http://securitytracker.com/id/1036144"
                    },
                    {
                        "name": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f",
                        "refsource": "CONFIRM",
                        "url": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f"
                    }
                ]
            }
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": [
                    {
                        "children": [],
                        "cpe_match": [
                            {
                                "cpe23Uri": "cpe:2.3:a:setroubleshoot_project:setroubleshoot:*:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "versionEndIncluding": "-",
                                "vulnerable": true
                            }
                        ],
                        "operator": "OR"
                    },
                    {
                        "children": [],
                        "cpe_match": [
                            {
                                "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_hpc_node:7.0:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            }
                        ],
                        "operator": "OR"
                    }
                ]
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2016-4989"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "setroubleshoot allows local users to bypass an intended container protection mechanism and execute arbitrary commands by (1) triggering an SELinux denial with a crafted file name, which is handled by the _set_tpath function in audit_data.py or via a crafted (2) local_id or (3) analysis_id field in a crafted XML document to the run_fix function in SetroubleshootFixit.py, related to the subprocess.check_output and commands.getstatusoutput functions, a different vulnerability than CVE-2016-4445."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "en",
                                    "value": "CWE-77"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "RHSA-2016:1267",
                            "refsource": "REDHAT",
                            "tags": [
                                "Third Party Advisory"
                            ],
                            "url": "https://rhn.redhat.com/errata/RHSA-2016-1267.html"
                        },
                        {
                            "name": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad",
                            "refsource": "CONFIRM",
                            "tags": [
                                "Patch"
                            ],
                            "url": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad"
                        },
                        {
                            "name": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f",
                            "refsource": "CONFIRM",
                            "tags": [
                                "Patch"
                            ],
                            "url": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461",
                            "refsource": "CONFIRM",
                            "tags": [
                                "Issue Tracking"
                            ],
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461"
                        },
                        {
                            "name": "RHSA-2016:1293",
                            "refsource": "REDHAT",
                            "tags": [
                                "Third Party Advisory"
                            ],
                            "url": "https://access.redhat.com/errata/RHSA-2016:1293"
                        },
                        {
                            "name": "1036144",
                            "refsource": "SECTRACK",
                            "tags": [
                                "Patch",
                                "Third Party Advisory"
                            ],
                            "url": "http://securitytracker.com/id/1036144"
                        },
                        {
                            "name": "[oss-security] 20160621 SELinux troubles",
                            "refsource": "MLIST",
                            "tags": [
                                "Mailing List",
                                "Third Party Advisory"
                            ],
                            "url": "http://seclists.org/oss-sec/2016/q2/574"
                        }
                    ]
                }
            },
            "impact": {
                "baseMetricV2": {
                    "cvssV2": {
                        "accessComplexity": "MEDIUM",
                        "accessVector": "LOCAL",
                        "authentication": "NONE",
                        "availabilityImpact": "COMPLETE",
                        "baseScore": 6.9,
                        "confidentialityImpact": "COMPLETE",
                        "integrityImpact": "COMPLETE",
                        "vectorString": "AV:L/AC:M/Au:N/C:C/I:C/A:C",
                        "version": "2.0"
                    },
                    "exploitabilityScore": 3.4,
                    "impactScore": 10.0,
                    "obtainAllPrivilege": false,
                    "obtainOtherPrivilege": false,
                    "obtainUserPrivilege": false,
                    "severity": "MEDIUM",
                    "userInteractionRequired": false
                },
                "baseMetricV3": {
                    "cvssV3": {
                        "attackComplexity": "HIGH",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.0,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
                        "version": "3.0"
                    },
                    "exploitabilityScore": 1.0,
                    "impactScore": 5.9
                }
            },
            "lastModifiedDate": "2017-04-17T16:36Z",
            "publishedDate": "2017-04-11T18:59Z"
        }
    }
}